fail_fast: true
repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.1
  hooks:
    - id: check-merge-conflict
    - id: detect-private-key
    - id: fix-encoding-pragma
    - id: check-yaml
    - id: debug-statements
    - id: end-of-file-fixer
    - id: flake8
      args: ['--ignore=E, W, --show-source=True']
    - id: trailing-whitespace
    - id: no-commit-to-branch

- repo: https://github.com/ambv/black
  rev: stable
  hooks:
    - id: black
      language_version: python3.7
